# Generated by Django 2.1.7 on 2019-09-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
