# Generated by Django 2.1.7 on 2019-09-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20190912_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='period',
            field=models.PositiveIntegerField(default=1, help_text="Please dont go over eight, you're gonna confuse my program"),
        ),
    ]
