# Generated by Django 2.1.7 on 2019-09-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20190912_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='period',
            field=models.PositiveIntegerField(choices=[(1, 'Period 1'), (2, 'Period 2'), (3, 'Period 3'), (4, 'Period 4'), (5, 'Period 5'), (6, 'Period 6'), (7, 'Period 7'), (8, 'Period 8')], default=1),
        ),
    ]
